kind: Namespace
apiVersion: v1
metadata:
  name: bookinfo
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  - bookinfo